### ISSUE TITLE
Bild bei Über uns Page wird doppelt angezeigt

### ISSUE THREAD

**Issue by Logggee** [Logggee/Web2Praktikum#6]
Bild für die Größe des Bereichs zu klein.

**Comment by Alextrfy** [comment]
background-size: cover 
Sollte es beheben

**Comment by Logggee** [comment]
> background-size: cover Sollte es beheben

ist schon drinn

**Comment by JayW39** [comment]
IMG aus HTML entfernt. So wird nur der div als image genutzt mit dem automatischen request
